Repository rob006-software/flarum-translations, pull requests merged in 2020-12, with the labels that each got.

#392 Add sycho/flarum-github-milestone
  config/components.php
Labels: ext-accepted

#397 Migrate reflar-doorman to fof-doorman
  README.md
  config/components.php
  sources/fof-doorman.json
  status/ja.md
  status/pl.md
  status/tr.md
  status/zh_Hans.md
  translations/ja/fof-doorman.json
  translations/pl/fof-doorman.json
  translations/tr/fof-doorman.json
  translations/zh_Hans/fof-doorman.json
Labels: ext-accepted, ext-cleanup

#383 Add luuhai48/oauth-google
  config/components.php
Labels: ext-accepted

#398 Add luuhai48/oauth-linkedin
  config/components.php
Labels: ext-accepted

#407 Migrate reflar-cookie-consent to fof-cookie-consent
  README.md
  config/components.php
  sources/fof-cookie-consent.json
  status/ja.md
  status/pl.md
  status/tr.md
  status/zh_Hans.md
  translations/ja/fof-cookie-consent.json
  translations/pl/fof-cookie-consent.json
  translations/tr/fof-cookie-consent.json
  translations/zh_Hans/fof-cookie-consent.json
Labels: ext-accepted, ext-cleanup

#409 Add flarum/nicknames
  config/components.php
Labels: ext-accepted

#391 Add sycho/flarum-action-log
  config/components.php
Labels: ext-accepted

#417 Add ianm/synopsis
  config/components.php
Labels: ext-accepted

#418 Migrate reflar-webhooks to fof-webhooks
  README.md
  config/components.php
  sources/fof-webhooks.json
  status/ja.md
  status/pl.md
  status/tr.md
  status/zh_Hans.md
  translations/ja/fof-webhooks.json
  translations/pl/fof-webhooks.json
  translations/tr/fof-webhooks.json
  translations/zh_Hans/fof-webhooks.json
Labels: ext-accepted, ext-cleanup

#421 Fix `ja` and `zh_Hans` repo name (config)
  config/subsplits.php
Labels: language-pack

#422 Fix `ja` and `zh_Hans` repo name (README.md)
  README.md
Labels: language-pack

#413 Add ianm/follow-users
  config/components.php
Labels: ext-accepted

#426 Exclude `the-turk` extensions from TR translations
  config/languages.php
Labels: language-pack
