Repository rob006-software/flarum-translations, pull requests merged in 2020-05, with the labels that each got.

#288 Add fof/discussion-language
  config/fof-project.php
Labels: ext-accepted

#294 Migrate flagrow-impersonate to fof-impersonate
  config/fof-project.php
  config/various-project.php
  sources/fof/fof-impersonate.json
  translations/fof/pl/fof-impersonate.json
  translations/fof/tr/fof-impersonate.json
Labels: ext-accepted, ext-cleanup

#296 Remove zerosonesfun-announce
  config/various-project.php
  sources/various/zerosonesfun-announce.json
  translations/various/pl/zerosonesfun-announce.json
  translations/various/tr/zerosonesfun-announce.json
Labels: ext-cleanup

#297 Add flarumite/flarum-decontaminator
  config/various-project.php
Labels: ext-accepted

#298 Add itnt/flarum-uitab
  config/various-project.php
Labels: ext-accepted

#299 Add the-turk/flarum-extended-appearance
  config/various-project.php
Labels: ext-accepted

#300 Add askvortsov/flarum-copy-links
  config/various-project.php
Labels: ext-accepted

#305 Add the-turk/flarum-ext-fancybox
  config/various-project.php
Labels: ext-accepted

#307 Add support for premium extensions
  config/premium-extensions.php
  config/various-project.php
Labels: ext-accepted

#308 Add askvortsov/flarum-discussion-templates
  config/various-project.php
Labels: ext-accepted

#309 Add flarumite/simple-discussion-views
  config/various-project.php
Labels: ext-accepted

#310 Add v17development/flarum-support
  config/various-project.php
Labels: ext-accepted

#311 Disable exporting premium extensions in `pl` subsplit
  config/subsplits.php
Labels: enhancement
