Repository rob006-software/flarum-translations, pull requests merged in 2020-02, with the labels that each got.

#245 Remove manelizzard/flarum-ext-notify (no release with 0.1.0-beta.8 support)
  config/various-project.php
  sources/various/manelizzard-notify.json
  translations/various/pl/manelizzard-notify.json
  translations/various/tr/manelizzard-notify.json
Labels: ext-cleanup

#246 Add the-turk/flarum-stargazing-theme
  config/various-project.php
Labels: ext-accepted

#247 Add therealsujitk/flarum-ext-show-password
  config/various-project.php
Labels: ext-accepted

#250 Migrate flagrow-upload to fof-upload
  config/fof-project.php
  config/various-project.php
  sources/fof/fof-upload.json
  translations/fof/pl/fof-upload.json
  translations/fof/tr/fof-upload.json
Labels: ext-accepted, ext-cleanup

#251 Add the-turk/flarum-diff
  config/various-project.php
Labels: ext-accepted

#252 Add askvortsov/flarum-saml
  config/various-project.php
Labels: ext-accepted

#253 Add askvortsov/flarum-auth-sync
  config/various-project.php
Labels: ext-accepted

#255 Add fof/filter
  config/fof-project.php
Labels: ext-accepted

#259 Add nomiscz/flarum-ext-auth-wechat
  config/various-project.php
Labels: ext-accepted

#260 Add the-turk/flarum-edit-notifications
  config/various-project.php
Labels: ext-accepted

#261 Add clarkwinkelmann/flarum-ext-silent-mailchimp
  config/various-project.php
Labels: ext-accepted

#262 Add clarkwinkelmann/flarum-ext-see-past-first-post
  config/various-project.php
Labels: ext-accepted

#263 Add the-turk/flarum-quiet-edits
  config/various-project.php
Labels: ext-accepted

#264 Add fof/moderator-notes
  config/fof-project.php
Labels: ext-accepted

#265 Add clarkwinkelmann/flarum-ext-who-read
  config/various-project.php
Labels: ext-accepted
