Repository rob006-software/flarum-translations, pull requests merged in 2020-11, with the labels that each got.

#370 Add clarkwinkelmann/flarum-ext-bookmarks
  config/components.php
Labels: ext-accepted

#384 Add clarkwinkelmann/flarum-ext-group-list
  config/components.php
Labels: ext-accepted

#388 Migrate kilowhat-mailing to clarkwinkelmann-mailing
  config/components.php
  sources/clarkwinkelmann-mailing.json
  translations/ja/clarkwinkelmann-mailing.json
  translations/pl/clarkwinkelmann-mailing.json
  translations/tr/clarkwinkelmann-mailing.json
  translations/zh_Hans/clarkwinkelmann-mailing.json
Labels: ext-accepted, ext-cleanup

#386 Add v17development/flarum-blog
  config/components.php
Labels: ext-pending
