Repository rob006-software/flarum-translations, pull requests merged in 2020-07, with the labels that each got.

#327 Migrate kilowhat-audit to kilowhat-audit-pro
  config/components.php
  sources/kilowhat-audit-pro.json
  translations/pl/kilowhat-audit-pro.json
  translations/tr/kilowhat-audit-pro.json
  translations/zh_Hans/kilowhat-audit-pro.json
Labels: ext-accepted, ext-cleanup

#326 Add kilowhat/flarum-ext-audit-free
  config/components.php
Labels: ext-accepted

#331 Remove clarkwinkelmann-post-date
  config/components.php
  sources/clarkwinkelmann-post-date.json
  translations/pl/clarkwinkelmann-post-date.json
  translations/tr/clarkwinkelmann-post-date.json
  translations/zh_Hans/clarkwinkelmann-post-date.json
Labels: ext-cleanup

#324 Add clarkwinkelmann/flarum-ext-popular-discussion-badge
  config/components.php
Labels: ext-accepted

#325 Add clarkwinkelmann/flarum-ext-likes-received
  config/components.php
Labels: ext-accepted

#332 Add nearata/flarum-ext-minecraft-avatars
  config/components.php
Labels: ext-accepted

#334 Add the-turk/flarum-welcome-widgets
  config/components.php
Labels: ext-accepted

#336 Add the-turk/flarum-regrole
  config/components.php
Labels: ext-accepted

#304 Add subsplit for `zh_Hans`
  config/subsplits.php
Labels: enhancement

#337 Add nearata/flarum-ext-embed-video
  config/components.php
Labels: ext-accepted
