Repository rob006-software/flarum-translations, pull requests merged in 2020-03, with the labels that each got.

#266 Add askvortsov/flarum-help-tags
  config/various-project.php
Labels: ext-accepted

#268 Update translations for core (beta 12)
  config/flarum-project.php
Labels: ext-cleanup

#269 Add clarkwinkelmann/flarum-ext-scratchpad
  config/various-project.php
Labels: ext-accepted

#270 Remove sources for branches from config
  config/fof-project.php
  config/various-project.php
Labels: enhancement

#271 Remove ignored extensions for PL language
  config/languages.php
Labels: enhancement

#272 Cleanup outdated translations for PL and TR
  translations/flarum/pl/core.json
  translations/flarum/tr/core.json
  translations/fof/pl/fof-best-answer.json
  translations/fof/pl/fof-byobu.json
  translations/fof/pl/fof-masquerade.json
  translations/fof/pl/fof-polls.json
  translations/fof/pl/fof-pwned-passwords.json
  translations/fof/pl/fof-upload.json
  translations/fof/pl/fof-username-request.json
  translations/fof/tr/fof-best-answer.json
  translations/fof/tr/fof-byobu.json
  translations/fof/tr/fof-masquerade.json
  translations/fof/tr/fof-pwned-passwords.json
  translations/fof/tr/fof-upload.json
  translations/fof/tr/fof-username-request.json
  translations/various/pl/askvortsov-saml.json
  translations/various/pl/clarkwinkelmann-author-change.json
  translations/various/pl/datitisev-dashboard.json
  translations/various/pl/dem13n-nickname-changer.json
  translations/various/pl/dem13n-quad-theme.json
  translations/various/pl/kilowhat-mailing.json
  translations/various/pl/tank-perspective.json
  translations/various/pl/the-turk-diff.json
  translations/various/pl/the-turk-mathren.json
  translations/various/pl/the-turk-password-strength.json
  translations/various/pl/tpokorra-post-notification.json
  translations/various/pl/ziymed-backtowebsite.json
  translations/various/tr/askvortsov-saml.json
  translations/various/tr/clarkwinkelmann-author-change.json
  translations/various/tr/dem13n-nickname-changer.json
  translations/various/tr/dem13n-quad-theme.json
  translations/various/tr/kilowhat-mailing.json
  translations/various/tr/nikovonlas-web-push.json
  translations/various/tr/tank-perspective.json
  translations/various/tr/the-turk-diff.json
  translations/various/tr/the-turk-mathren.json
  translations/various/tr/the-turk-password-strength.json
  translations/various/tr/tpokorra-post-notification.json
  translations/various/tr/ziymed-backtowebsite.json
Labels: enhancement

#273 Add therealsujitk/flarum-ext-gifs
  config/various-project.php
Labels: ext-accepted

#274 Add askvortsov/flarum-moderator-strikes
  config/various-project.php
Labels: ext-accepted

#275 Remove askvortsov-moderator-strikes
  config/various-project.php
  sources/various/askvortsov-moderator-strikes.json
  translations/various/pl/askvortsov-moderator-strikes.json
  translations/various/tr/askvortsov-moderator-strikes.json
Labels: ext-cleanup

#276 Add studosi/mail-filter
  config/various-project.php
Labels: ext-accepted

#278 Add askvortsov/flarum-categories
  config/various-project.php
Labels: ext-accepted

#281 Migrate flagrow-passport to fof-passport
  config/fof-project.php
  config/various-project.php
  sources/fof/fof-passport.json
  translations/fof/pl/fof-passport.json
  translations/fof/tr/fof-passport.json
Labels: ext-accepted, ext-cleanup

#277 Add askvortsov/flarum-moderator-warnings
  config/various-project.php
Labels: ext-accepted

#283 Add therealsujitk/flarum-ext-hljs
  config/various-project.php
Labels: ext-accepted

#282 Add askvortsov/flarum-pwa
  config/various-project.php
Labels: ext-accepted
