Repository rob006-software/flarum-translations, pull requests merged in 2020-01, with the labels that each got.

#215 Add the-turk/flarum-mathren
  config/various-project.php
Labels: ext-accepted

#212 Add minr/flarum-ext-auth-qq
  config/various-project.php
Labels: ext-accepted

#216 Add minr/flarum-ext-auth-weibo
  config/various-project.php
Labels: ext-accepted

#231 Add clarkwinkelmann/flarum-ext-email-as-display-name
  config/various-project.php
Labels: ext-accepted

#232 Add clarkwinkelmann/flarum-ext-passwordless
  config/various-project.php
Labels: ext-accepted

#233 Add clarkwinkelmann/flarum-ext-create-user-modal
  config/various-project.php
Labels: ext-accepted

#234 Add dem13n/quad-theme
  config/various-project.php
Labels: ext-accepted

#235 Add the-turk/flarum-password-strength
  config/various-project.php
Labels: ext-accepted

#236 Revert "Add dem13n/quad-theme"
  config/various-project.php
Labels: ext-cleanup

#230 Add xelson/flarum-ext-chat
  config/various-project.php
Labels: ext-accepted

#237 Add dem13n/quad-theme
  config/various-project.php
Labels: ext-accepted

#238 Add simonxeko/follow-users
  config/various-project.php
Labels: ext-accepted

#239 Add simonxeko/preview-discussion
  config/various-project.php
Labels: ext-accepted

#242 Update config for core and validation components
  config/flarum-project.php
Labels: ext-cleanup

#244 Fix release reference for tituspijean-auth-ssowat config
  config/various-project.php
Labels: enhancement
