Repository rob006-software/flarum-translations, pull requests merged in 2021-05, with the labels that each got.

#519 Remove `nearata/flarum-ext-no-self-likes`
  config/components.php
  sources/nearata-no-self-likes.json
  translations/es/nearata-no-self-likes.json
  translations/fr/nearata-no-self-likes.json
  translations/it/nearata-no-self-likes.json
  translations/ja/nearata-no-self-likes.json
  translations/ka/nearata-no-self-likes.json
  translations/nl/nearata-no-self-likes.json
  translations/pl/nearata-no-self-likes.json
  translations/si/nearata-no-self-likes.json
  translations/tr/nearata-no-self-likes.json
  translations/zh_Hans/nearata-no-self-likes.json
Labels: ext-cleanup

#520 Remove `dem13n/quad-theme`
  config/components.php
  sources/dem13n-quad-theme.json
  translations/es/dem13n-quad-theme.json
  translations/fr/dem13n-quad-theme.json
  translations/it/dem13n-quad-theme.json
  translations/ja/dem13n-quad-theme.json
  translations/ka/dem13n-quad-theme.json
  translations/nl/dem13n-quad-theme.json
  translations/pl/dem13n-quad-theme.json
  translations/si/dem13n-quad-theme.json
  translations/tr/dem13n-quad-theme.json
  translations/zh_Hans/dem13n-quad-theme.json
Labels: ext-cleanup

#522 Add miniflar/sidenav-download-button
  config/components.php
Labels: ext-accepted

#521 Add justoverclock/flarum-ext-infocards
  config/components.php
Labels: ext-accepted

#524 Add justoverclock/flarum-ext-pwgen
  config/components.php
Labels: ext-accepted

#523 Add tituspijean/flarum-ext-auth-ldap
  config/components.php
  config/languages.php
  sources/tituspijean-auth-ldap.json
  translations/fr/tituspijean-auth-ldap.json
  translations/ja/tituspijean-auth-ldap.json
  translations/ka/tituspijean-auth-ldap.json
  translations/pl/tituspijean-auth-ldap.json
  translations/tr/tituspijean-auth-ldap.json
  translations/zh_Hans/tituspijean-auth-ldap.json
Labels: ext-accepted

#525 Add justoverclock/flarum-ext-toastme
  config/components.php
Labels: ext-accepted

#526 Add miniflar/admin-notepad-widget
  config/components.php
Labels: ext-accepted

#527 Add justoverclock/flarum-ext-newsletter
  config/components.php
Labels: ext-accepted

#528 Add justoverclock/flarum-ext-dontgoaway
  config/components.php
Labels: ext-accepted

#531 Add justoverclock/flarum-ext-newsfeed
  config/components.php
Labels: ext-accepted

#534 Add nearata/flarum-ext-auth-minecraft
  config/components.php
Labels: ext-accepted

#535 Add justoverclock/flarum-ext-realtimecode
  config/components.php
Labels: ext-accepted

#536 Add clarkwinkelmann/flarum-ext-predefined-avatars
  config/components.php
Labels: ext-accepted

#541 Add justoverclock/flarum-ext-readmore
  config/components.php
Labels: ext-accepted

#542 Add justoverclock/flarum-ext-keywords
  config/components.php
Labels: ext-accepted

#543 Add askvortsov/flarum-auto-moderator
  config/components.php
Labels: ext-accepted

#547 Add support for Latvian language pack
  config/languages.php
  config/subsplits.php
Labels: language-pack

#553 Remove `flarumi/oauth-instagram`
  config/components.php
  sources/flarumi-oauth-instagram.json
  translations/es/flarumi-oauth-instagram.json
  translations/et/flarumi-oauth-instagram.json
  translations/fr/flarumi-oauth-instagram.json
  translations/it/flarumi-oauth-instagram.json
  translations/ja/flarumi-oauth-instagram.json
  translations/ka/flarumi-oauth-instagram.json
  translations/lv/flarumi-oauth-instagram.json
  translations/nl/flarumi-oauth-instagram.json
  translations/pl/flarumi-oauth-instagram.json
  translations/si/flarumi-oauth-instagram.json
  translations/tr/flarumi-oauth-instagram.json
  translations/zh_Hans/flarumi-oauth-instagram.json
Labels: ext-cleanup

#554 Change repo URL for Turkish language pack
  README.md
  config/subsplits.php
Labels: language-pack

#556 Add glowingblue/redis-setup
  config/components.php
Labels: ext-accepted
