Repository rob006-software/flarum-translations, pull requests merged in 2021-09, with the labels that each got.

#705 Add `askvortsov/flarum-article-series`
  config/components.php
Labels: ext-accepted

#704 Add `justoverclock/last-users-posts`
  config/components.php
Labels: ext-accepted

#708 Add `justoverclock/hot-discussions`
  config/components.php
Labels: ext-accepted

#711 Add Azerbaijani language
  README.md
  config/languages.php
  config/subsplits.php
Labels: language-pack

#712 Add `justoverclock/discussion-info`
  config/components.php
Labels: ext-accepted

#713 Add Russian language
  README.md
  config/languages.php
  config/subsplits.php
  translations/ru/clarkwinkelmann-author-change.json
  translations/ru/clarkwinkelmann-bookmarks.json
  translations/ru/core.json
  translations/ru/flarum-akismet.json
  translations/ru/flarum-approval.json
  translations/ru/flarum-emoji.json
  translations/ru/flarum-flags.json
  translations/ru/flarum-likes.json
  translations/ru/flarum-lock.json
  translations/ru/flarum-markdown.json
  translations/ru/flarum-mentions.json
  translations/ru/flarum-nicknames.json
  translations/ru/flarum-pusher.json
  translations/ru/flarum-statistics.json
  translations/ru/flarum-sticky.json
  translations/ru/flarum-subscriptions.json
  translations/ru/flarum-suspend.json
  translations/ru/flarum-tags.json
  translations/ru/fof-byobu.json
  translations/ru/fof-cookie-consent.json
  translations/ru/fof-custom-footer.json
  translations/ru/fof-default-group.json
  translations/ru/fof-discussion-language.json
  translations/ru/fof-drafts.json
  translations/ru/fof-formatting.json
  translations/ru/fof-forum-statistics-widget.json
  translations/ru/fof-github-sponsors.json
  translations/ru/fof-html-errors.json
  translations/ru/fof-ignore-users.json
  translations/ru/fof-merge-discussions.json
  translations/ru/fof-moderator-notes.json
  translations/ru/fof-oauth.json
  translations/ru/fof-open-collective.json
  translations/ru/fof-polls.json
  translations/ru/fof-pwned-passwords.json
  translations/ru/fof-recaptcha.json
  translations/ru/fof-secure-https.json
  translations/ru/fof-share-social.json
  translations/ru/fof-socialprofile.json
  translations/ru/fof-spamblock.json
  translations/ru/fof-split.json
  translations/ru/fof-upload.json
  translations/ru/fof-user-bio.json
  translations/ru/fof-user-directory.json
  translations/ru/validation.json
Labels: language-pack

#715 Add `justoverclock/discussion-hero-showtags`
  config/components.php
Labels: ext-accepted

#717 Add `justoverclock/related-discussions`
  config/components.php
Labels: ext-accepted

#718 Add `clarkwinkelmann/flarum-ext-featured-discussions`
  config/components.php
Labels: ext-accepted

#719 Add `justoverclock/imdb-api`
  config/components.php
Labels: ext-accepted

#720 Add `davwheat/flarum-ext-share`
  config/components.php
Labels: ext-accepted

#724 Remove `justoverclock/image-gallery` (abandoned)
  config/components.php
  sources/justoverclock-image-gallery.json
  translations/ar/justoverclock-image-gallery.json
  translations/az/justoverclock-image-gallery.json
  translations/cs/justoverclock-image-gallery.json
  translations/de/justoverclock-image-gallery.json
  translations/es/justoverclock-image-gallery.json
  translations/et/justoverclock-image-gallery.json
  translations/fa/justoverclock-image-gallery.json
  translations/fi/justoverclock-image-gallery.json
  translations/fr/justoverclock-image-gallery.json
  translations/hi/justoverclock-image-gallery.json
  translations/hu/justoverclock-image-gallery.json
  translations/it/justoverclock-image-gallery.json
  translations/ja/justoverclock-image-gallery.json
  translations/ka/justoverclock-image-gallery.json
  translations/lt/justoverclock-image-gallery.json
  translations/lv/justoverclock-image-gallery.json
  translations/ml/justoverclock-image-gallery.json
  translations/ms/justoverclock-image-gallery.json
  translations/nl/justoverclock-image-gallery.json
  translations/pl/justoverclock-image-gallery.json
  translations/pt/justoverclock-image-gallery.json
  translations/pt_BR/justoverclock-image-gallery.json
  translations/ru/justoverclock-image-gallery.json
  translations/si/justoverclock-image-gallery.json
  translations/sk/justoverclock-image-gallery.json
  translations/ta/justoverclock-image-gallery.json
  translations/te/justoverclock-image-gallery.json
  translations/th/justoverclock-image-gallery.json
  translations/tr/justoverclock-image-gallery.json
  translations/vi/justoverclock-image-gallery.json
  translations/zh_Hans/justoverclock-image-gallery.json
Labels: ext-cleanup
