Repository rob006-software/flarum-translations, pull requests merged in 2021-06, with the labels that each got.

#557 Add malago/flarum-ads
  config/components.php
  sources/malago-ads.json
  translations/es/malago-ads.json
  translations/et/malago-ads.json
  translations/fr/malago-ads.json
  translations/it/malago-ads.json
  translations/ja/malago-ads.json
  translations/ka/malago-ads.json
  translations/lv/malago-ads.json
  translations/nl/malago-ads.json
  translations/pl/malago-ads.json
  translations/si/malago-ads.json
  translations/tr/malago-ads.json
  translations/zh_Hans/malago-ads.json
Labels: ext-accepted

#560 Add support for Czech language pack
  config/languages.php
  config/subsplits.php
  translations/cs/core.json
  translations/cs/flarum-akismet.json
  translations/cs/flarum-approval.json
  translations/cs/flarum-emoji.json
  translations/cs/flarum-flags.json
  translations/cs/flarum-likes.json
  translations/cs/flarum-lock.json
  translations/cs/flarum-markdown.json
  translations/cs/flarum-mentions.json
  translations/cs/flarum-pusher.json
  translations/cs/flarum-statistics.json
  translations/cs/flarum-sticky.json
  translations/cs/flarum-subscriptions.json
  translations/cs/flarum-suspend.json
  translations/cs/flarum-tags.json
  translations/cs/validation.json
Labels: language-pack

#565 Update Dutch language pack repository
  README.md
  config/subsplits.php
Labels: language-pack

#564 Add clarkwinkelmann/flarum-ext-translation-inspector
  config/components.php
Labels: ext-accepted

#573 Add clarkwinkelmann/flarum-ext-shadow-ban
  config/components.php
Labels: ext-accepted

#572 Remove `fof/transliterator`
  config/components.php
  sources/fof-transliterator.json
  translations/cs/fof-transliterator.json
  translations/es/fof-transliterator.json
  translations/et/fof-transliterator.json
  translations/fr/fof-transliterator.json
  translations/it/fof-transliterator.json
  translations/ja/fof-transliterator.json
  translations/ka/fof-transliterator.json
  translations/lv/fof-transliterator.json
  translations/nl/fof-transliterator.json
  translations/pl/fof-transliterator.json
  translations/si/fof-transliterator.json
  translations/tr/fof-transliterator.json
  translations/zh_Hans/fof-transliterator.json
Labels: ext-cleanup

#574 Remove redundant translations for languages that are already translated in extension itself
  config/languages.php
Labels: enhancement

#577 Add `justoverclock/flarum-ext-hashtag`
  config/components.php
Labels: ext-accepted

#583 Add `clarkwinkelmann/flarum-ext-post-bookmarks`
  config/components.php
Labels: ext-accepted

#589 Add Hindi language
  README.md
  config/languages.php
  config/subsplits.php
Labels: language-pack

#590 Add Telugu language
  README.md
  config/languages.php
  config/subsplits.php
Labels: language-pack

#593 Update Sinhala language pack repository
  README.md
  config/subsplits.php
Labels: language-pack

#594 Update French language pack repository
  README.md
  config/subsplits.php
Labels: language-pack

#592 Add `justoverclock/flarum-ext-purify`
  config/components.php
Labels: ext-accepted

#600 Add Tamil language
  README.md
  config/languages.php
  config/subsplits.php
Labels: language-pack

#587 Add `nyu8/flarum-email-filter`
  config/components.php
Labels: ext-pending

#591 Add `the-turk/flarum-pallet-theme`
  config/components.php
  config/languages.php
Labels: ext-accepted

#580 Add `serakoi/flarumdiscordtheme`
  config/components.php
Labels: ext-accepted

#602 Add `clarkwinkelmann/flarum-ext-external-email-validation`
  config/components.php
Labels: ext-accepted

#603 Add `the-turk/flarum-mathren`
  config/components.php
  sources/the-turk-mathren.json
  translations/fr/the-turk-mathren.json
  translations/ja/the-turk-mathren.json
  translations/ka/the-turk-mathren.json
  translations/pl/the-turk-mathren.json
  translations/zh_Hans/the-turk-mathren.json
Labels: ext-accepted

#604 Add `the-turk/flarum-regrole`
  config/components.php
  sources/the-turk-regrole.json
  translations/fr/the-turk-regrole.json
  translations/ja/the-turk-regrole.json
  translations/ka/the-turk-regrole.json
  translations/pl/the-turk-regrole.json
  translations/zh_Hans/the-turk-regrole.json
Labels: ext-accepted

#605 Add `ianm/level-ranks`
  config/components.php
  sources/ianm-level-ranks.json
  translations/cs/ianm-level-ranks.json
  translations/es/ianm-level-ranks.json
  translations/et/ianm-level-ranks.json
  translations/fr/ianm-level-ranks.json
  translations/it/ianm-level-ranks.json
  translations/ja/ianm-level-ranks.json
  translations/ka/ianm-level-ranks.json
  translations/lv/ianm-level-ranks.json
  translations/nl/ianm-level-ranks.json
  translations/pl/ianm-level-ranks.json
  translations/si/ianm-level-ranks.json
  translations/tr/ianm-level-ranks.json
  translations/zh_Hans/ianm-level-ranks.json
Labels: ext-accepted

#609 Add Lithuanian language
  README.md
  config/languages.php
  config/subsplits.php
  translations/lt/core.json
  translations/lt/flarum-akismet.json
  translations/lt/flarum-approval.json
  translations/lt/flarum-emoji.json
  translations/lt/flarum-flags.json
  translations/lt/flarum-likes.json
  translations/lt/flarum-lock.json
  translations/lt/flarum-markdown.json
  translations/lt/flarum-mentions.json
  translations/lt/flarum-nicknames.json
  translations/lt/flarum-pusher.json
  translations/lt/flarum-statistics.json
  translations/lt/flarum-sticky.json
  translations/lt/flarum-subscriptions.json
  translations/lt/flarum-suspend.json
  translations/lt/flarum-tags.json
  translations/lt/validation.json
Labels: language-pack

#610 Add `the-turk/flarum-diff`
  config/components.php
  sources/the-turk-diff.json
  translations/cs/the-turk-diff.json
  translations/es/the-turk-diff.json
  translations/et/the-turk-diff.json
  translations/fr/the-turk-diff.json
  translations/hi/the-turk-diff.json
  translations/it/the-turk-diff.json
  translations/ja/the-turk-diff.json
  translations/ka/the-turk-diff.json
  translations/lt/the-turk-diff.json
  translations/lv/the-turk-diff.json
  translations/nl/the-turk-diff.json
  translations/pl/the-turk-diff.json
  translations/si/the-turk-diff.json
  translations/ta/the-turk-diff.json
  translations/te/the-turk-diff.json
  translations/zh_Hans/the-turk-diff.json
Labels: ext-accepted

#611 Add `the-turk/flarum-miserable-users`
  config/components.php
Labels: ext-accepted

#532 Add zerosonesfun/expired-posts
  config/components.php
Labels: ext-accepted

#615 Add `ianm/gravatar`
  config/components.php
Labels: ext-accepted

#616 Add Malayalam language
  README.md
  config/languages.php
  config/subsplits.php
Labels: language-pack

#618 Add Portuguese (Brazil) language
  README.md
  config/languages.php
  config/subsplits.php
  translations/pt_BR/core.json
  translations/pt_BR/flarum-akismet.json
  translations/pt_BR/flarum-approval.json
  translations/pt_BR/flarum-emoji.json
  translations/pt_BR/flarum-flags.json
  translations/pt_BR/flarum-likes.json
  translations/pt_BR/flarum-lock.json
  translations/pt_BR/flarum-markdown.json
  translations/pt_BR/flarum-mentions.json
  translations/pt_BR/flarum-pusher.json
  translations/pt_BR/flarum-statistics.json
  translations/pt_BR/flarum-sticky.json
  translations/pt_BR/flarum-subscriptions.json
  translations/pt_BR/flarum-suspend.json
  translations/pt_BR/flarum-tags.json
  translations/pt_BR/validation.json
Labels: language-pack

#617 Add `afrux/asirem`
  config/components.php
Labels: ext-accepted
