Repository rob006-software/flarum-translations, pull requests merged in 2021-07, with the labels that each got.

#619 Add `the-turk/flarum-nodp`
  config/components.php
Labels: ext-accepted

#621 Add Persian language
  README.md
  config/languages.php
  config/subsplits.php
  translations/fa/core.json
  translations/fa/flarum-akismet.json
  translations/fa/flarum-approval.json
  translations/fa/flarum-emoji.json
  translations/fa/flarum-flags.json
  translations/fa/flarum-likes.json
  translations/fa/flarum-lock.json
  translations/fa/flarum-markdown.json
  translations/fa/flarum-mentions.json
  translations/fa/flarum-pusher.json
  translations/fa/flarum-statistics.json
  translations/fa/flarum-sticky.json
  translations/fa/flarum-subscriptions.json
  translations/fa/flarum-suspend.json
  translations/fa/flarum-tags.json
  translations/fa/validation.json
Labels: language-pack

#622 Add config for GitHub actions
  .github/workflows/update.yml
Labels: infrastructure

#623 Add `malago/flarum-linkpreview`
  config/components.php
Labels: ext-accepted

#612 Add `spookygames/flarum-ext-auth-keycloak`
  config/components.php
  config/languages.php
Labels: ext-accepted

#607 Add `the-turk/flarum-stickiest`
  config/components.php
Labels: ext-accepted

#625 Add `acpl/my-tags`
  config/components.php
Labels: ext-accepted

#624 Add `datitisev/flarum-webhooks-pro`
  config/components.php
  sources/datitisev-webhooks-pro.json
  translations/cs/datitisev-webhooks-pro.json
  translations/es/datitisev-webhooks-pro.json
  translations/et/datitisev-webhooks-pro.json
  translations/fr/datitisev-webhooks-pro.json
  translations/it/datitisev-webhooks-pro.json
  translations/ja/datitisev-webhooks-pro.json
  translations/ka/datitisev-webhooks-pro.json
  translations/lv/datitisev-webhooks-pro.json
  translations/nl/datitisev-webhooks-pro.json
  translations/pl/datitisev-webhooks-pro.json
  translations/si/datitisev-webhooks-pro.json
  translations/tr/datitisev-webhooks-pro.json
  translations/zh_Hans/datitisev-webhooks-pro.json
Labels: ext-accepted

#628 Add Slovak language
  README.md
  config/languages.php
  config/subsplits.php
  translations/sk/core.json
  translations/sk/flarum-akismet.json
  translations/sk/flarum-approval.json
  translations/sk/flarum-emoji.json
  translations/sk/flarum-flags.json
  translations/sk/flarum-likes.json
  translations/sk/flarum-lock.json
  translations/sk/flarum-markdown.json
  translations/sk/flarum-mentions.json
  translations/sk/flarum-nicknames.json
  translations/sk/flarum-pusher.json
  translations/sk/flarum-statistics.json
  translations/sk/flarum-sticky.json
  translations/sk/flarum-subscriptions.json
  translations/sk/flarum-suspend.json
  translations/sk/flarum-tags.json
  translations/sk/validation.json
Labels: language-pack

#629 Add `extiverse/mercury`
  config/components.php
Labels: ext-accepted

#631 Add Arabic language
  README.md
  config/languages.php
  config/subsplits.php
Labels: language-pack

#632 Remove `afrux/asirem`
  config/components.php
  sources/afrux-asirem.json
  translations/cs/afrux-asirem.json
  translations/es/afrux-asirem.json
  translations/et/afrux-asirem.json
  translations/fa/afrux-asirem.json
  translations/fr/afrux-asirem.json
  translations/hi/afrux-asirem.json
  translations/it/afrux-asirem.json
  translations/ja/afrux-asirem.json
  translations/ka/afrux-asirem.json
  translations/lt/afrux-asirem.json
  translations/lv/afrux-asirem.json
  translations/ml/afrux-asirem.json
  translations/nl/afrux-asirem.json
  translations/pl/afrux-asirem.json
  translations/pt_BR/afrux-asirem.json
  translations/si/afrux-asirem.json
  translations/sk/afrux-asirem.json
  translations/ta/afrux-asirem.json
  translations/te/afrux-asirem.json
  translations/tr/afrux-asirem.json
  translations/zh_Hans/afrux-asirem.json
Labels: ext-cleanup

#635 Add `justoverclock/flarum-ext-feedback`
  config/components.php
Labels: ext-accepted

#637 Add `the-turk/flarum-flamoji`
  config/components.php
Labels: ext-accepted

#640 Remove redundant translations for languages that are already translated in extension itself
  config/languages.php
Labels: enhancement

#644 Add Hungarian language
  README.md
  config/languages.php
  config/subsplits.php
  translations/hu/core.json
  translations/hu/flarum-akismet.json
  translations/hu/flarum-approval.json
  translations/hu/flarum-emoji.json
  translations/hu/flarum-flags.json
  translations/hu/flarum-likes.json
  translations/hu/flarum-lock.json
  translations/hu/flarum-markdown.json
  translations/hu/flarum-mentions.json
  translations/hu/flarum-pusher.json
  translations/hu/flarum-statistics.json
  translations/hu/flarum-sticky.json
  translations/hu/flarum-subscriptions.json
  translations/hu/flarum-suspend.json
  translations/hu/flarum-tags.json
  translations/hu/validation.json
Labels: language-pack

#645 Add `the-turk/flarum-quiet-edits`
  config/components.php
  sources/the-turk-quiet-edits.json
  translations/fr/the-turk-quiet-edits.json
  translations/ja/the-turk-quiet-edits.json
  translations/ka/the-turk-quiet-edits.json
  translations/pl/the-turk-quiet-edits.json
  translations/zh_Hans/the-turk-quiet-edits.json
Labels: ext-accepted

#648 Add `justoverclock/first-visit-indexpage`
  config/components.php
Labels: ext-accepted

#649 Add Malay language
  README.md
  config/languages.php
  config/subsplits.php
Labels: language-pack

#651 Add `justoverclock/custom-header`
  config/components.php
Labels: ext-accepted

#653 Add Portuguese language
  README.md
  config/languages.php
  config/subsplits.php
  translations/pt/core.json
  translations/pt/flarum-akismet.json
  translations/pt/flarum-approval.json
  translations/pt/flarum-emoji.json
  translations/pt/flarum-flags.json
  translations/pt/flarum-likes.json
  translations/pt/flarum-lock.json
  translations/pt/flarum-markdown.json
  translations/pt/flarum-mentions.json
  translations/pt/flarum-pusher.json
  translations/pt/flarum-statistics.json
  translations/pt/flarum-sticky.json
  translations/pt/flarum-subscriptions.json
  translations/pt/flarum-suspend.json
  translations/pt/flarum-tags.json
  translations/pt/validation.json
Labels: language-pack

#654 Add `justoverclock/header-slideshow`
  config/components.php
Labels: ext-accepted

#642 Add `katosdev/signature`
  config/components.php
Labels: ext-accepted

#529 Add nearata/flarum-ext-twofactor
  config/components.php
Labels: ext-accepted

#444 Add malago/flarum-ext-fancybox
  config/components.php
Labels: ext-accepted

#601 Add `hehongyuanlove/flarum-auth-qq`
  config/components.php
Labels: ext-pending

#517 Add nearata/flarum-ext-dsts
  config/components.php
Labels: ext-accepted

#657 Add `acpl/mobile-tab`
  config/components.php
Labels: ext-accepted

#658 Add `justoverclock/image-gallery`
  config/components.php
Labels: ext-accepted

#659 Add `maicol07/flarum-oidc-client`
  config/components.php
Labels: ext-accepted

#660 Add `ralkage/flarum-hcaptcha`
  config/components.php
Labels: ext-accepted

#661 Add `kyrne/whisper`
  config/components.php
Labels: ext-accepted

#662 Remove `malago/flarum-linkpreview`
  config/components.php
  sources/malago-linkpreview.json
  translations/ar/malago-linkpreview.json
  translations/cs/malago-linkpreview.json
  translations/de/malago-linkpreview.json
  translations/es/malago-linkpreview.json
  translations/et/malago-linkpreview.json
  translations/fa/malago-linkpreview.json
  translations/fr/malago-linkpreview.json
  translations/hi/malago-linkpreview.json
  translations/hu/malago-linkpreview.json
  translations/it/malago-linkpreview.json
  translations/ja/malago-linkpreview.json
  translations/ka/malago-linkpreview.json
  translations/lt/malago-linkpreview.json
  translations/lv/malago-linkpreview.json
  translations/ml/malago-linkpreview.json
  translations/ms/malago-linkpreview.json
  translations/nl/malago-linkpreview.json
  translations/pl/malago-linkpreview.json
  translations/pt/malago-linkpreview.json
  translations/pt_BR/malago-linkpreview.json
  translations/si/malago-linkpreview.json
  translations/sk/malago-linkpreview.json
  translations/ta/malago-linkpreview.json
  translations/te/malago-linkpreview.json
  translations/tr/malago-linkpreview.json
  translations/zh_Hans/malago-linkpreview.json
Labels: ext-cleanup

#664 Add `justoverclock/og-meta-tag`
  config/components.php
Labels: ext-accepted

#663 Add `justoverclock/username-blacklist`
  config/components.php
Labels: ext-accepted

#665 Add Thai language
  README.md
  config/languages.php
  config/subsplits.php
  translations/th/core.json
  translations/th/flarum-likes.json
  translations/th/flarum-mentions.json
  translations/th/flarum-subscriptions.json
  translations/th/flarum-tags.json
Labels: language-pack

#667 Remove `tank/perspective`
  config/components.php
  sources/tank-perspective.json
  translations/ar/tank-perspective.json
  translations/cs/tank-perspective.json
  translations/de/tank-perspective.json
  translations/es/tank-perspective.json
  translations/et/tank-perspective.json
  translations/fa/tank-perspective.json
  translations/fr/tank-perspective.json
  translations/hi/tank-perspective.json
  translations/hu/tank-perspective.json
  translations/it/tank-perspective.json
  translations/ja/tank-perspective.json
  translations/ka/tank-perspective.json
  translations/lt/tank-perspective.json
  translations/lv/tank-perspective.json
  translations/ml/tank-perspective.json
  translations/ms/tank-perspective.json
  translations/nl/tank-perspective.json
  translations/pl/tank-perspective.json
  translations/pt/tank-perspective.json
  translations/pt_BR/tank-perspective.json
  translations/si/tank-perspective.json
  translations/sk/tank-perspective.json
  translations/ta/tank-perspective.json
  translations/te/tank-perspective.json
  translations/th/tank-perspective.json
  translations/tr/tank-perspective.json
  translations/zh_Hans/tank-perspective.json
Labels: ext-cleanup

#558 Add serakoi/flarum-hideprofile
  config/components.php
Labels: ext-accepted
