Repository rob006-software/flarum-translations, pull requests merged in 2021-02, with the labels that each got.

#460 Add kyrne/aegis
  config/components.php
Labels: ext-accepted

#461 Remove reflar-twofactor
  sources/reflar-twofactor.json
  translations/ja/reflar-twofactor.json
  translations/ka/reflar-twofactor.json
  translations/pl/reflar-twofactor.json
  translations/tr/reflar-twofactor.json
  translations/zh_Hans/reflar-twofactor.json
Labels: ext-cleanup

#462 Add glowingblue/password-strength
  config/components.php
  config/languages.php
  sources/glowingblue-password-strength.json
  translations/ja/glowingblue-password-strength.json
  translations/ka/glowingblue-password-strength.json
  translations/pl/glowingblue-password-strength.json
  translations/zh_Hans/glowingblue-password-strength.json
Labels: ext-accepted

#463 Add blomstra/readme
  config/components.php
Labels: ext-accepted

#464 Add blomstra/realtime
  config/components.php
Labels: ext-accepted

#467 Add support for French language pack
  README.md
  config/languages.php
  config/subsplits.php
  translations/fr/core.json
  translations/fr/flarum-akismet.json
  translations/fr/flarum-approval.json
  translations/fr/flarum-emoji.json
  translations/fr/flarum-flags.json
  translations/fr/flarum-likes.json
  translations/fr/flarum-lock.json
  translations/fr/flarum-markdown.json
  translations/fr/flarum-mentions.json
  translations/fr/flarum-nicknames.json
  translations/fr/flarum-pusher.json
  translations/fr/flarum-statistics.json
  translations/fr/flarum-sticky.json
  translations/fr/flarum-subscriptions.json
  translations/fr/flarum-suspend.json
  translations/fr/flarum-tags.json
  translations/fr/validation.json
Labels: language-pack

#458 Add dem13n/discussion-cards
  config/components.php
Labels: ext-accepted
