Repository rob006-software/flarum-translations, pull requests merged in 2022-08, with the labels that each got.

#906 Exclude `kilowhat-formulaire` from French language
  config/languages.php
  translations/fr/kilowhat-formulaire.json
Labels: language-pack

#907 Add `tohsakarat/save-and-load-draft-automatically`
  config/components.php
Labels: ext-accepted

#909 Add `ianm/no-meta-title`
  config/components.php
Labels: ext-accepted

#911 Add `clarkwinkelmann/flarum-ext-selective-mediaembed`
  config/components.php
Labels: ext-accepted

#912 Add `tohsakarat/tags-filter`
  config/components.php
Labels: ext-accepted

#914 Add `clarkwinkelmann/flarum-ext-ipsum-autocomplete`
  config/components.php
Labels: ext-accepted

#915 Add `clarkwinkelmann/flarum-ext-discussion-bookmarks`
  config/components.php
Labels: ext-accepted

#917 Remove `clarkwinkelmann/flarum-ext-bookmarks`
  config/components.php
  sources/clarkwinkelmann-bookmarks.json
  translations/ar/clarkwinkelmann-bookmarks.json
  translations/az/clarkwinkelmann-bookmarks.json
  translations/bn/clarkwinkelmann-bookmarks.json
  translations/cs/clarkwinkelmann-bookmarks.json
  translations/da/clarkwinkelmann-bookmarks.json
  translations/de/clarkwinkelmann-bookmarks.json
  translations/es/clarkwinkelmann-bookmarks.json
  translations/et/clarkwinkelmann-bookmarks.json
  translations/fa/clarkwinkelmann-bookmarks.json
  translations/fi/clarkwinkelmann-bookmarks.json
  translations/fr/clarkwinkelmann-bookmarks.json
  translations/he/clarkwinkelmann-bookmarks.json
  translations/hi/clarkwinkelmann-bookmarks.json
  translations/hu/clarkwinkelmann-bookmarks.json
  translations/it/clarkwinkelmann-bookmarks.json
  translations/ja/clarkwinkelmann-bookmarks.json
  translations/ka/clarkwinkelmann-bookmarks.json
  translations/ko/clarkwinkelmann-bookmarks.json
  translations/lt/clarkwinkelmann-bookmarks.json
  translations/lv/clarkwinkelmann-bookmarks.json
  translations/ml/clarkwinkelmann-bookmarks.json
  translations/nl/clarkwinkelmann-bookmarks.json
  translations/pl/clarkwinkelmann-bookmarks.json
  translations/pt/clarkwinkelmann-bookmarks.json
  translations/pt_BR/clarkwinkelmann-bookmarks.json
  translations/ru/clarkwinkelmann-bookmarks.json
  translations/si/clarkwinkelmann-bookmarks.json
  translations/sk/clarkwinkelmann-bookmarks.json
  translations/sr/clarkwinkelmann-bookmarks.json
  translations/sv/clarkwinkelmann-bookmarks.json
  translations/ta/clarkwinkelmann-bookmarks.json
  translations/te/clarkwinkelmann-bookmarks.json
  translations/th/clarkwinkelmann-bookmarks.json
  translations/tr/clarkwinkelmann-bookmarks.json
  translations/uz/clarkwinkelmann-bookmarks.json
  translations/vi/clarkwinkelmann-bookmarks.json
  translations/zh_Hans/clarkwinkelmann-bookmarks.json
Labels: ext-cleanup

#926 Add translations for Hungarian subsplit
  config/subsplitsLocale/hu.json
Labels: language-pack
