Repository rob006-software/flarum-translations, pull requests merged in 2023-01, with the labels that each got.

#993 Add `ziiven/flarum-money-leaderboard`
  config/components.php
  config/languages.php
Labels: ext-accepted

#994 Remove `finteger/shorts`
  cache/extiverse.json
  config/components.php
  sources/finteger-shorts.json
  translations/ar/finteger-shorts.json
  translations/az/finteger-shorts.json
  translations/bn/finteger-shorts.json
  translations/cs/finteger-shorts.json
  translations/da/finteger-shorts.json
  translations/de/finteger-shorts.json
  translations/es/finteger-shorts.json
  translations/et/finteger-shorts.json
  translations/fa/finteger-shorts.json
  translations/fi/finteger-shorts.json
  translations/fr/finteger-shorts.json
  translations/he/finteger-shorts.json
  translations/hi/finteger-shorts.json
  translations/hu/finteger-shorts.json
  translations/it/finteger-shorts.json
  translations/ja/finteger-shorts.json
  translations/ka/finteger-shorts.json
  translations/ko/finteger-shorts.json
  translations/lt/finteger-shorts.json
  translations/lv/finteger-shorts.json
  translations/ml/finteger-shorts.json
  translations/nl/finteger-shorts.json
  translations/pl/finteger-shorts.json
  translations/pt/finteger-shorts.json
  translations/pt_BR/finteger-shorts.json
  translations/ro/finteger-shorts.json
  translations/ru/finteger-shorts.json
  translations/si/finteger-shorts.json
  translations/sk/finteger-shorts.json
  translations/sr/finteger-shorts.json
  translations/sv/finteger-shorts.json
  translations/ta/finteger-shorts.json
  translations/te/finteger-shorts.json
  translations/th/finteger-shorts.json
  translations/tr/finteger-shorts.json
  translations/uk/finteger-shorts.json
  translations/uz/finteger-shorts.json
  translations/vi/finteger-shorts.json
  translations/zh_Hans/finteger-shorts.json
  translations/zh_Hant/finteger-shorts.json
Labels: ext-cleanup

#995 Remove `itnt/flarum-uitab`
  sources/itnt-uitab.json
  translations/ar/itnt-uitab.json
  translations/az/itnt-uitab.json
  translations/bn/itnt-uitab.json
  translations/cs/itnt-uitab.json
  translations/da/itnt-uitab.json
  translations/de/itnt-uitab.json
  translations/es/itnt-uitab.json
  translations/et/itnt-uitab.json
  translations/fa/itnt-uitab.json
  translations/fi/itnt-uitab.json
  translations/fr/itnt-uitab.json
  translations/he/itnt-uitab.json
  translations/hi/itnt-uitab.json
  translations/hu/itnt-uitab.json
  translations/it/itnt-uitab.json
  translations/ja/itnt-uitab.json
  translations/ka/itnt-uitab.json
  translations/ko/itnt-uitab.json
  translations/lt/itnt-uitab.json
  translations/lv/itnt-uitab.json
  translations/ml/itnt-uitab.json
  translations/nl/itnt-uitab.json
  translations/pl/itnt-uitab.json
  translations/pt/itnt-uitab.json
  translations/pt_BR/itnt-uitab.json
  translations/ro/itnt-uitab.json
  translations/ru/itnt-uitab.json
  translations/si/itnt-uitab.json
  translations/sk/itnt-uitab.json
  translations/sr/itnt-uitab.json
  translations/sv/itnt-uitab.json
  translations/ta/itnt-uitab.json
  translations/te/itnt-uitab.json
  translations/th/itnt-uitab.json
  translations/tr/itnt-uitab.json
  translations/uk/itnt-uitab.json
  translations/uz/itnt-uitab.json
  translations/vi/itnt-uitab.json
  translations/zh_Hans/itnt-uitab.json
  translations/zh_Hant/itnt-uitab.json
Labels: ext-cleanup

#996 Remove `finteger/ratings`
  sources/finteger-ratings.json
  translations/ar/finteger-ratings.json
  translations/az/finteger-ratings.json
  translations/bn/finteger-ratings.json
  translations/cs/finteger-ratings.json
  translations/da/finteger-ratings.json
  translations/de/finteger-ratings.json
  translations/es/finteger-ratings.json
  translations/et/finteger-ratings.json
  translations/fa/finteger-ratings.json
  translations/fi/finteger-ratings.json
  translations/fr/finteger-ratings.json
  translations/he/finteger-ratings.json
  translations/hi/finteger-ratings.json
  translations/hu/finteger-ratings.json
  translations/it/finteger-ratings.json
  translations/ja/finteger-ratings.json
  translations/ka/finteger-ratings.json
  translations/ko/finteger-ratings.json
  translations/lt/finteger-ratings.json
  translations/lv/finteger-ratings.json
  translations/ml/finteger-ratings.json
  translations/nl/finteger-ratings.json
  translations/pl/finteger-ratings.json
  translations/pt/finteger-ratings.json
  translations/pt_BR/finteger-ratings.json
  translations/ro/finteger-ratings.json
  translations/ru/finteger-ratings.json
  translations/si/finteger-ratings.json
  translations/sk/finteger-ratings.json
  translations/sr/finteger-ratings.json
  translations/sv/finteger-ratings.json
  translations/ta/finteger-ratings.json
  translations/te/finteger-ratings.json
  translations/th/finteger-ratings.json
  translations/tr/finteger-ratings.json
  translations/uk/finteger-ratings.json
  translations/uz/finteger-ratings.json
  translations/vi/finteger-ratings.json
  translations/zh_Hans/finteger-ratings.json
  translations/zh_Hant/finteger-ratings.json
Labels: ext-cleanup

#997 Add Catalan language
  config/languages.php
  config/subsplits.php
Labels: language-pack

#998 Add `ziiven/flarum-raffle-ticket`
  config/components.php
Labels: ext-accepted

#999 Add `justoverclock/export-post-to-pdf`
  config/components.php
Labels: ext-accepted

#1000 Add `ianm/oauth-reddit`
  config/components.php
Labels: ext-accepted
